### ISSUE TITLE
Error: Cannot find module "ionic-marquee"

### ISSUE THREAD

**Issue by jecorrales3** [pengkobe/ionic-marquee#1]
Hi, 

I was installing _ionic-marquee_ for my project and I'm getting this error: Error: Cannot find module "ionic-marquee", can you help me?

**Install process:**

> npm install ionic-marquee --save

**My Code:**
Imports in app.module.ts

> import {IonMarqueeModule} from "ionic-marquee";
>  
> @NgModule({
>  ...
>  imports: [
>    IonMarqueeModule,
>    ...
>  ],
>  ...
> })
> export class AppModule {}

>

**Comment by duckls** [comment]
遇到同样问题

**Comment by nadeemkhan** [comment]
+1

**Comment by ExceedLimits** [comment]
+1

**Comment by ExceedLimits** [comment]
Any news?

**Comment by A491382** [comment]
+1

**Comment by kingyyy** [comment]
same here no news

**Comment by pengkobe** [comment]
sorry guys. I've been fixed it at `0.3.0`.
